apiVersion: v1
kind: Service
metadata:
  name: eureka-server

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: eureka-server

  ports:
    - name: http
      port: 8761
      targetPort: 8761
      nodePort: 30061

  type: NodePort
