apiVersion: app/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  #minReadySeconds: 30 #30 seconds delay after ready all its pods and replicaset
  selector:
    matchLabels:
      app: eureka-server  
  replicas: 1
  template: #template for the pods
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: assaduzzaman/eureka-server:pi