spring:
  output:
    ansi:
  datasource:
    url: jdbc:postgresql://localhost:5433/yugabyte
    username: yugabyte
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: false
  #  r2dbc:
#    url: r2dbc:postgresql://localhost:5433/qcloud
#    username: yugabyte
##    password: 12345
  liquibase:
#    url: jdbc:postgresql://localhost:5433/yugabyte
#    user: yugabyte
#    password: 12345
    default-schema: qapi
    drop-first: false
    change-log: classpath:/db/changelog/db.changelog-master.yml
