server:
  port: 8080
spring:
  application:
    name: qapi
  profiles:
    active: '@active.profile@'
  output:
    ansi:
      enabled: always
logging:
  level:
    io.netty.resolver.dns.DnsServerAddressStreamProviders: off
    com: error
    queue.pro: error
    liquibase: error
    org:
      jboss: error
      springframework: error
      postgresql: error
      hibernate:
        query: error
        cfg: error
        type: error
        boot: error
        integrator: error
        service: error
        engine: error
        resource: error
        validator: error
        jpa: error
        internal: error
        event: error
        stat: error
        cache: error
        sql: error
        type.descriptor.sql.BasicBinder: error