spring:
  docker:
    compose:
      lifecycle-management: start-only
      file: ./docker-compose-pg.yaml
      profiles:
        active: "pg-container"
  output:
    ansi:
      enabled: always
  security:
      oauth2:
        resource-server:
          jwt:
            issuer-uri: https://idpv2.oss.net.bd/realms/q-cloud
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        show_sql: false
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/token
    username: testuser
    password: testuser
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      auto-commit: false
  #  r2dbc:
#    url: r2dbc:postgresql://localhost:5433/qcloud
#    username: yugabyte
##    password: 12345
  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    default-schema: ${spring.jpa.properties.hibernate.default_schema}
    drop-first: false
    change-log: classpath:/db/changelog/db.changelog-master.yml
#logging:
#  level:
#    com: debug
#    queue.pro: info
#    liquibase: error
#    reactor: debug
#    org:
#      springframework: debug
#      springframework.orm.jpa: debug
#      hibernate:
#        persister: error
#        stat: debug
#        cache: error
#        sql: debug
#        type.descriptor.sql.BasicBinder: trace
#    root: debug