version: '3.7'
services:
  eureka-server:
    container_name: eureka-server
    build: ./eureka-server
    ports:
      - 8761:8761
  tollrate-service:
    container_name: tollrate-service
    build: ./eureka-tollrate-service
    ports: 
      - 8085:8085
    depends_on: 
      - eureka-server
  fastpass-service:
    container_name: fastpass-service
    build: ./eureka-fastpass-service
    ports:
      - 8086:8086
    depends_on: 
      - eureka-server
  fastpass-console:
    container_name: fastpass-console
    build: ./eureka-fastpass-console
    ports:
      - 8082:8082
    depends_on: 
      - fastpass-service
  tollrate-billboard:
    container_name: tollrate-billboard
    build: ./eureka-tollrate-billboard
    ports: 
      - 8081:8081
    depends_on: 
      - tollrate-service