apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: eureka-server
  name: eureka-server
  selfLink: /api/v1/namespaces/default/services/eureka-server
spec:
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
    nodePort: 30080
  selector:
    run: eureka-server
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
