apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv-nfs
  labels:
    type: demo-pv-nfs
spec:
  storageClassName: manual
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.17.10.12
    path: "/nfs_data/demo_data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
  namespace: test-env
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Mi 
