piVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: fastpass-service
  name: fastpass-service
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/fastpass-service
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: fastpass-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: fastpass-service
    spec:
      containers:
      - image: registry.gitlab.com/assad-group/spring-cloud:eureka-fastpass-service
        imagePullPolicy: Always
        name: fastpass-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
        - name: gitlab-registry  
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: fastpass-service
  name: fastpass-service
  selfLink: /api/v1/namespaces/default/services/fastpass-service
spec:
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
    nodePort: 30086
  selector:
    run: fastpass-service
  sessionAffinity: None
  type: NodePort
status:

