piVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: fastpass-console
  name: fastpass-console
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/fastpass-console
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: fastpass-console
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: fastpass-console
    spec:
      containers:
      - image: registry.gitlab.com/assad-group/spring-cloud:fastpass-console
        imagePullPolicy: Always
        name: fastpass-console
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
        - name: gitlab-registry  
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: fastpass-console
  name: fastpass-console
  selfLink: /api/v1/namespaces/default/services/fastpass-console
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
    nodePort: 30082
  selector:
    run: fastpass-console
  sessionAffinity: None
  type: NodePort
status:

