apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  externalIPs:
  - 192.168.8.252
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  type: NodePort # work for any type follow https://kubernetes.io/docs/concepts/services-networking/service/#external-ips document
status:
  loadBalancer: {}
