apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbit-mq-nfs-pv01
  labels:
    type: rabbit-mq-nfs
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.103
    path: "/root/NFS_DATA/K8DATA/rabitmq"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbit-mq-nfs-pv02
  labels:
    type: rabbit-mq-nfs
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.103
    path: "/root/NFS_DATA/K8DATA/rabitmq"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbit-mq-nfs-pv03
  labels:
    type: rabbit-mq-nfs
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.103
    path: "/root/NFS_DATA/K8DATA/rabitmq"
