apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: two-containers
  name: two-containers
spec:
  restartPolicy: Never

  containers:
  - image: nginx
    name: nginx-container
  - image: assaduzzaman/cron
    name: debian-container

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: two-containers
  name: two-containers
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30950
  selector:
    run: two-containers
  type: NodePort
status:
  loadBalancer: {}

# kubectl logs two-containers -c debian-container -f