version: '3.7'
services:
  eureka-server:
    container_name: eureka-server
    image: assaduzzaman/eureka-server:${TAG}
    ports:
      - 8761:8761
  fastpass-service:
    container_name: fastpass-service
    image: eureka-fastpass-service:crt
    ports:
      - 8086:8086
    depends_on: 
      -  eureka-server
  