server:
  port: 8086
  
spring:
  application:
    name: api-proxy
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
      
zuul:
  ignoredServices: '*'
  host:
   connect-timeout-millis: 20000
   socket-timeout-millis: 20000
  routes:
   trproxy:
     url: http://localhost:8085


  