server:
  port: 8087
  
spring:
  application:
    name: api-proxy
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  ignoredServices: '*'
  host:
   connect-timeout-millis: 20000
   socket-timeout-millis: 20000
  routes:
   trproxy:
     url: http://localhost:8086
     path: /tollproxy/**
     
     #http://localhost:8087/tollproxy/fastpass?fastpassid=100


  