#-------------Service-------------
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-broker
  namespace: $K8S_NAMESPACE
spec:
  selector:
    app: rabbitmq-broker
  ports:
    - name: queue-port
      port: 5672
      targetPort: 5672
    #  nodePort: 31672
    - name: admin-port
      port: 15672
      targetPort: 15672
      nodePort: 30672
  #type: ClusterIP
  type: NodePort
