server:
  port: 0
spring:
  application:
    name: tollrate-billboard
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int} # random.int or random.value
    prefer-ip-address: true

toll.rate.svc.location: http://tollrate-svc/tollrate/