apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-eureka-api-gw
  name: multi-eureka-api-gw
spec:
  containers:
  - image: assaduzzaman/multi-eureka-api-gw
    name: multi-eureka-api-gw
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}